- default:
  - Music: music
  - Start Making Games: http://stevejohnson.posterous.com/a-starting-point-for-making-games
  - Python Game Tutorial/Python Game Programming Tutorial: pyglettutorial
    pages: 6

- hidden:
  - Résumé: resume

- Toys:    
  - Art Project 1: art_project_1
  - Artack: artack
  - Bungie Chopper/Elite Bungie Chopper Squadron: bungie_chopper
  - gw0rp: gw0rp
  - Escort Wing: escort_wing
  - Space Train: spacetrain
  - Splatterboard: splatterboard

- Code:  
  - JTrie: http://www.github.com/irskep/jtrie
  - Regex compiler: http://www.github.com/irskep/regex_compiler
  - T-Reg: http://www.github.com/irskep/T-Reg

- Social:  
  - Hacker News: http://news.ycombinator.com/user?id=stevejohnson
  - Stack Overflow: http://stackoverflow.com/users/8061/steve-johnson
  - Hacker Résumé: hacker_resume
  - Stack Overflow CV: http://careers.stackoverflow.com/stevejohnson
